/** Headless interaction layer: selection, drag and drop, slash menu, shortcuts, input rules, clipboard and in-place editing. */
export { createInteraction, compatibleChartKinds } from './interaction.js';
export type { DataTransferLike, EditableHandle, Interaction, InteractionOptions, MenuAction, ShortcutContext } from './interaction.js';
export type { BlockMenuState, DragState, EditingState, InteractionState, PromptState, SlashState, SyncRequest, TextSelectionState } from './state.js';
export type { Box, Caret, ConflictInfo, FeedbackEvent, FeedbackKind, FieldKey, Platform, Placement } from './types.js';
export { attachInteraction, measureBlocks } from './surface.js';
export type { SurfaceBinding, SurfaceOptions } from './surface.js';
export { attachEditable } from './editable.js';
export type { EditableBinding, EditableOptions } from './editable.js';
export { CHART_TEMPLATES, SLASH_GROUPS, createSlashCatalog } from './catalog.js';
export type { SlashContext, SlashInput, SlashItem, SlashLabels } from './catalog.js';
export { filterSlashItems, fuzzyScore, groupSlashItems, slashScore } from './slash.js';
export type { SlashGroup } from './slash.js';
export { createShortcutRegistry, detectPlatform, formatShortcut, matchesShortcut, parseShortcut } from './shortcuts.js';
export type { KeyEventLike, ParsedShortcut, ShortcutDefinition, ShortcutInfo, ShortcutRegistry } from './shortcuts.js';
export { INPUT_RULE_DOCS, matchInputRule } from './input-rules.js';
export type { InputRuleMatch, InputRuleTrigger } from './input-rules.js';
export { TURN_INTO_TARGETS, blankContent, canTurnInto, convertContent, isConvertible, targetOf } from './convert.js';
export type { TurnIntoEntry, TurnIntoTarget } from './convert.js';
export { emptySelection, extendSelection, moveSelectionFocus, pruneSelection, selectAllBlocks, selectMany, selectOnly, selectionRange, toggleSelection } from './selection.js';
export type { SelectionState } from './selection.js';
export { hitTest as hitTestBlocks, indexLayout as indexBlockLayout, dropTargetAt, indicatorFor, isNoopPlacement, placementOf } from './drop.js';
export type { DropIndicator, DropOptions, DropPosition, DropTarget, LayoutBox, LayoutIndex } from './drop.js';
export { planBackspaceAtStart, planDeleteAtEnd, planEnter, editTargetFor } from './edit-plan.js';
export type { EditSubject } from './edit-plan.js';
export { planDelete, planDuplicate, planInsert, planMove, planStepMove, planTurnInto } from './plan.js';
export type { EditTarget, IdFactory, Plan, PlanResult } from './plan.js';
export { CLIPBOARD_MIME, parseBlocksPayload, planPaste, serializeBlocks } from './clipboard.js';
export type { ClipboardPayload, PasteContext, PastePlan } from './clipboard.js';
export { MARKS, deleteRange, highlightState, insertText, linkAt, markState, normalizeRuns as normalizeInlineRuns, replaceRange, runsPlainText, setHighlight, setLink, sliceRuns, splitRuns, toggleMark, wordRangeAt } from './inline.js';
export type { Mark, MarkState } from './inline.js';
export { getSelectionOffsets, readRunsFrom, renderRunsInto, selectionClientRect, setSelectionOffsets } from './inline-dom.js';
export { cellField, fieldKeys, fieldText, itemField, parseField, withFieldRuns, withFieldText } from './fields.js';
export { listChecked, listIndent, listNumbers, listSetChecked, listSetIndent, listSplice, tableAddColumn, tableAddRow, tableRemoveColumn, tableRemoveRow, tableSetAlign } from './structure.js';
export { patchChartSpec } from './chart-edit.js';
export type { ChartPatch } from './chart-edit.js';
export { depthOf as blockDepth, descendantsOf as blockDescendants, rootsOf as blockRoots, visibleOrder as visibleBlocks } from './tree.js';
